export const defaultTheme = {
  bg: "#fff",
  bgAlt: "#999",
  button: "#5b50c8",
  buttonHover: "#4F43C4",
  sidePanel: "lightgrey",
  border: "#222",
  color: "#495057",
  breakpoint: "200px",
  selectedTerm: "#ddd",
  selectedCourse: "grey",
  bgBody: "white",
  bgUI: "#414141",
  panelColor: "#D5D5D5",
  panelAlt: "#FFF",
  textColor: "#000",
  primaryColor: "#4F43C4",
  secondaryColor: "#AAA0F8",
  tertiaryColor: "#a49ee1",
};

export const darkmodeTheme = {
  ...defaultTheme,
  bg: "#0d1117",
  bgAlt: "#161b22",
  sidePanel: "darkgrey",
  border: "#ced4da",
  color: "white",
  selectedTerm: "#444",
  selectedCourse: "white",
  bgBody: "darkgrey",
  bgUI: "#30363d",
  panelColor: "#222",
  panelAlt: "#30363D",
  textColor: "#FFF",
};
