export const TOGGLE_DARKMODE = 'TOGGLE_DARKMODE';


// School Settings

export const SET_CURRENT_SCHOOL = 'SET_CURRENT_SCHOOL';
export const SET_SCHOOL_GRADES = 'SET_SCHOOL_GRADES';
export const LOAD_CUSTOM_SCHOOL = 'LOAD_CUSTOM_SCHOOL';

// Loading

export const LOAD_SETTINGS = 'LOAD_SETTINGS';